export const CATEGORIES = ["Weapons", "Tools", "Armor", "Materials", "Food", "Blocks", "Magic", "Enchanted Books"];

export const ITEM_DB = [
  // --- WEAPONS ---
  { id: "minecraft:wooden_sword", name: "Wooden Sword", cat: "Weapons", icon: "🗡️" },
  { id: "minecraft:stone_sword", name: "Stone Sword", cat: "Weapons", icon: "🗡️" },
  { id: "minecraft:iron_sword", name: "Iron Sword", cat: "Weapons", icon: "🗡️" },
  { id: "minecraft:golden_sword", name: "Golden Sword", cat: "Weapons", icon: "🗡️" },
  { id: "minecraft:diamond_sword", name: "Diamond Sword", cat: "Weapons", icon: "🗡️" },
  { id: "minecraft:netherite_sword", name: "Netherite Sword", cat: "Weapons", icon: "🗡️" },
  { id: "minecraft:bow", name: "Bow", cat: "Weapons", icon: "🏹" },
  { id: "minecraft:crossbow", name: "Crossbow", cat: "Weapons", icon: "🏹" },
  { id: "minecraft:trident", name: "Trident", cat: "Weapons", icon: "🔱" },
  { id: "minecraft:mace", name: "Mace", cat: "Weapons", icon: "🔨" },
  { id: "minecraft:shield", name: "Shield", cat: "Weapons", icon: "🛡️" },

  // --- TOOLS ---
  // Pickaxes
  { id: "minecraft:wooden_pickaxe", name: "Wooden Pickaxe", cat: "Tools", icon: "⛏️" },
  { id: "minecraft:stone_pickaxe", name: "Stone Pickaxe", cat: "Tools", icon: "⛏️" },
  { id: "minecraft:iron_pickaxe", name: "Iron Pickaxe", cat: "Tools", icon: "⛏️" },
  { id: "minecraft:golden_pickaxe", name: "Golden Pickaxe", cat: "Tools", icon: "⛏️" },
  { id: "minecraft:diamond_pickaxe", name: "Diamond Pickaxe", cat: "Tools", icon: "⛏️" },
  { id: "minecraft:netherite_pickaxe", name: "Netherite Pickaxe", cat: "Tools", icon: "⛏️" },
  // Axes
  { id: "minecraft:wooden_axe", name: "Wooden Axe", cat: "Tools", icon: "🪓" },
  { id: "minecraft:stone_axe", name: "Stone Axe", cat: "Tools", icon: "🪓" },
  { id: "minecraft:iron_axe", name: "Iron Axe", cat: "Tools", icon: "🪓" },
  { id: "minecraft:golden_axe", name: "Golden Axe", cat: "Tools", icon: "🪓" },
  { id: "minecraft:diamond_axe", name: "Diamond Axe", cat: "Tools", icon: "🪓" },
  { id: "minecraft:netherite_axe", name: "Netherite Axe", cat: "Tools", icon: "🪓" },
  // Shovels
  { id: "minecraft:wooden_shovel", name: "Wooden Shovel", cat: "Tools", icon: "⛏️" },
  { id: "minecraft:stone_shovel", name: "Stone Shovel", cat: "Tools", icon: "⛏️" },
  { id: "minecraft:iron_shovel", name: "Iron Shovel", cat: "Tools", icon: "⛏️" },
  { id: "minecraft:golden_shovel", name: "Golden Shovel", cat: "Tools", icon: "⛏️" },
  { id: "minecraft:diamond_shovel", name: "Diamond Shovel", cat: "Tools", icon: "⛏️" },
  { id: "minecraft:netherite_shovel", name: "Netherite Shovel", cat: "Tools", icon: "⛏️" },
  // Hoes
  { id: "minecraft:wooden_hoe", name: "Wooden Hoe", cat: "Tools", icon: "🪃" },
  { id: "minecraft:stone_hoe", name: "Stone Hoe", cat: "Tools", icon: "🪃" },
  { id: "minecraft:iron_hoe", name: "Iron Hoe", cat: "Tools", icon: "🪃" },
  { id: "minecraft:golden_hoe", name: "Golden Hoe", cat: "Tools", icon: "🪃" },
  { id: "minecraft:diamond_hoe", name: "Diamond Hoe", cat: "Tools", icon: "🪃" },
  { id: "minecraft:netherite_hoe", name: "Netherite Hoe", cat: "Tools", icon: "🪃" },
  { id: "minecraft:fishing_rod", name: "Fishing Rod", cat: "Tools", icon: "🎣" },
  { id: "minecraft:shears", name: "Shears", cat: "Tools", icon: "✂️" },
  { id: "minecraft:flint_and_steel", name: "Flint & Steel", cat: "Tools", icon: "🔥" },
  { id: "minecraft:spyglass", name: "Spyglass", cat: "Tools", icon: "🔭" },
  { id: "minecraft:lead", name: "Lead (Tali)", cat: "Tools", icon: "🪢" },

  // --- ARMOR ---
  // Leather
  { id: "minecraft:leather_helmet", name: "Leather Cap", cat: "Armor", icon: "🧢" },
  { id: "minecraft:leather_chestplate", name: "Leather Tunic", cat: "Armor", icon: "👕" },
  { id: "minecraft:leather_leggings", name: "Leather Pants", cat: "Armor", icon: "👖" },
  { id: "minecraft:leather_boots", name: "Leather Boots", cat: "Armor", icon: "🥾" },
  // Chainmail
  { id: "minecraft:chainmail_helmet", name: "Chainmail Helmet", cat: "Armor", icon: "🪖" },
  { id: "minecraft:chainmail_chestplate", name: "Chainmail Chest", cat: "Armor", icon: "👕" },
  { id: "minecraft:chainmail_leggings", name: "Chainmail Legs", cat: "Armor", icon: "👖" },
  { id: "minecraft:chainmail_boots", name: "Chainmail Boots", cat: "Armor", icon: "🥾" },
  // Iron
  { id: "minecraft:iron_helmet", name: "Iron Helmet", cat: "Armor", icon: "🪖" },
  { id: "minecraft:iron_chestplate", name: "Iron Chestplate", cat: "Armor", icon: "👕" },
  { id: "minecraft:iron_leggings", name: "Iron Leggings", cat: "Armor", icon: "👖" },
  { id: "minecraft:iron_boots", name: "Iron Boots", cat: "Armor", icon: "🥾" },
  // Gold
  { id: "minecraft:golden_helmet", name: "Golden Helmet", cat: "Armor", icon: "🪖" },
  { id: "minecraft:golden_chestplate", name: "Golden Chestplate", cat: "Armor", icon: "👕" },
  { id: "minecraft:golden_leggings", name: "Golden Leggings", cat: "Armor", icon: "👖" },
  { id: "minecraft:golden_boots", name: "Golden Boots", cat: "Armor", icon: "🥾" },
  // Diamond
  { id: "minecraft:diamond_helmet", name: "Diamond Helmet", cat: "Armor", icon: "🪖" },
  { id: "minecraft:diamond_chestplate", name: "Diamond Chestplate", cat: "Armor", icon: "👕" },
  { id: "minecraft:diamond_leggings", name: "Diamond Leggings", cat: "Armor", icon: "👖" },
  { id: "minecraft:diamond_boots", name: "Diamond Boots", cat: "Armor", icon: "🥾" },
  // Netherite
  { id: "minecraft:netherite_helmet", name: "Netherite Helmet", cat: "Armor", icon: "🪖" },
  { id: "minecraft:netherite_chestplate", name: "Netherite Chest", cat: "Armor", icon: "👕" },
  { id: "minecraft:netherite_leggings", name: "Netherite Legs", cat: "Armor", icon: "👖" },
  { id: "minecraft:netherite_boots", name: "Netherite Boots", cat: "Armor", icon: "🥾" },
  { id: "minecraft:turtle_helmet", name: "Turtle Helmet", cat: "Armor", icon: "🐢" },

  // --- MATERIALS ---
  { id: "minecraft:coal", name: "Coal", cat: "Materials", icon: "⚫" },
  { id: "minecraft:raw_iron", name: "Raw Iron", cat: "Materials", icon: "🪨" },
  { id: "minecraft:iron_ingot", name: "Iron Ingot", cat: "Materials", icon: "⚪" },
  { id: "minecraft:raw_gold", name: "Raw Gold", cat: "Materials", icon: "🪨" },
  { id: "minecraft:gold_ingot", name: "Gold Ingot", cat: "Materials", icon: "🟡" },
  { id: "minecraft:diamond", name: "Diamond", cat: "Materials", icon: "💎" },
  { id: "minecraft:emerald", name: "Emerald", cat: "Materials", icon: "🟩" },
  { id: "minecraft:lapis_lazuli", name: "Lapis Lazuli", cat: "Materials", icon: "🔵" },
  { id: "minecraft:redstone", name: "Redstone Dust", cat: "Materials", icon: "🔴" },
  { id: "minecraft:netherite_scrap", name: "Netherite Scrap", cat: "Materials", icon: "🪨" },
  { id: "minecraft:netherite_ingot", name: "Netherite Ingot", cat: "Materials", icon: "🌑" },
  { id: "minecraft:copper_ingot", name: "Copper Ingot", cat: "Materials", icon: "🟠" },
  { id: "minecraft:quartz", name: "Nether Quartz", cat: "Materials", icon: "🤍" },
  { id: "minecraft:stick", name: "Stick", cat: "Materials", icon: "🪵" },
  { id: "minecraft:leather", name: "Leather", cat: "Materials", icon: "🐄" },
  { id: "minecraft:string", name: "String", cat: "Materials", icon: "🧵" },
  { id: "minecraft:slime_ball", name: "Slimeball", cat: "Materials", icon: "🟢" },
  { id: "minecraft:gunpowder", name: "Gunpowder", cat: "Materials", icon: "💣" },
  { id: "minecraft:bone", name: "Bone", cat: "Materials", icon: "🦴" },
  { id: "minecraft:blaze_rod", name: "Blaze Rod", cat: "Materials", icon: "🔥" },
  { id: "minecraft:ender_pearl", name: "Ender Pearl", cat: "Materials", icon: "🔮" },

  // --- FOOD ---
  { id: "minecraft:apple", name: "Apple", cat: "Food", icon: "🍎" },
  { id: "minecraft:golden_apple", name: "Golden Apple", cat: "Food", icon: "🍎" },
  { id: "minecraft:enchanted_golden_apple", name: "Ench Golden Apple", cat: "Food", icon: "🍎✨" },
  { id: "minecraft:carrot", name: "Carrot", cat: "Food", icon: "🥕" },
  { id: "minecraft:golden_carrot", name: "Golden Carrot", cat: "Food", icon: "🥕" },
  { id: "minecraft:potato", name: "Potato", cat: "Food", icon: "🥔" },
  { id: "minecraft:baked_potato", name: "Baked Potato", cat: "Food", icon: "🥔" },
  { id: "minecraft:bread", name: "Bread", cat: "Food", icon: "🍞" },
  { id: "minecraft:cooked_beef", name: "Steak", cat: "Food", icon: "🥩" },
  { id: "minecraft:cooked_porkchop", name: "Cooked Porkchop", cat: "Food", icon: "🍖" },
  { id: "minecraft:cooked_mutton", name: "Cooked Mutton", cat: "Food", icon: "🍖" },
  { id: "minecraft:cooked_chicken", name: "Cooked Chicken", cat: "Food", icon: "🍗" },
  { id: "minecraft:cooked_salmon", name: "Cooked Salmon", cat: "Food", icon: "🍣" },
  { id: "minecraft:sweet_berries", name: "Sweet Berries", cat: "Food", icon: "🫐" },
  { id: "minecraft:melon_slice", name: "Melon Slice", cat: "Food", icon: "🍉" },

  // --- BLOCKS ---
  { id: "minecraft:stone", name: "Stone", cat: "Blocks", icon: "🪨" },
  { id: "minecraft:cobblestone", name: "Cobblestone", cat: "Blocks", icon: "🪨" },
  { id: "minecraft:dirt", name: "Dirt", cat: "Blocks", icon: "🟤" },
  { id: "minecraft:grass_block", name: "Grass Block", cat: "Blocks", icon: "🟩" },
  { id: "minecraft:oak_log", name: "Oak Log", cat: "Blocks", icon: "🪵" },
  { id: "minecraft:oak_planks", name: "Oak Planks", cat: "Blocks", icon: "🪵" },
  { id: "minecraft:glass", name: "Glass", cat: "Blocks", icon: "🪟" },
  { id: "minecraft:obsidian", name: "Obsidian", cat: "Blocks", icon: "⬛" },
  { id: "minecraft:bedrock", name: "Bedrock", cat: "Blocks", icon: "⚫" },
  { id: "minecraft:diamond_block", name: "Diamond Block", cat: "Blocks", icon: "🧊" },
  { id: "minecraft:iron_block", name: "Iron Block", cat: "Blocks", icon: "⬜" },
  { id: "minecraft:gold_block", name: "Gold Block", cat: "Blocks", icon: "🟨" },

  // --- MAGIC & RARE ---
  { id: "minecraft:totem_of_undying", name: "Totem of Undying", cat: "Magic", icon: "🗿" },
  { id: "minecraft:elytra", name: "Elytra", cat: "Magic", icon: "🦋" },
  { id: "minecraft:experience_bottle", name: "Bottle o' Enchanting", cat: "Magic", icon: "🧪" },
  { id: "minecraft:beacon", name: "Beacon", cat: "Magic", icon: "🏮" },
  { id: "minecraft:conduit", name: "Conduit", cat: "Magic", icon: "🧿" },
  { id: "minecraft:heart_of_the_sea", name: "Heart of the Sea", cat: "Magic", icon: "💙" },
  { id: "minecraft:nether_star", name: "Nether Star", cat: "Magic", icon: "⭐" },
  { id: "minecraft:dragon_egg", name: "Dragon Egg", cat: "Magic", icon: "🥚" },
  { id: "minecraft:shulker_box", name: "Shulker Box", cat: "Magic", icon: "📦" },
  { id: "minecraft:saddle", name: "Saddle", cat: "Magic", icon: "🐎" },
];

export const ENCHANTMENTS = [
  { id: "minecraft:sharpness", name: "Sharpness" },
  { id: "minecraft:smite", name: "Smite" },
  { id: "minecraft:bane_of_arthropods", name: "Bane of Arthropods" },
  { id: "minecraft:knockback", name: "Knockback" },
  { id: "minecraft:fire_aspect", name: "Fire Aspect" },
  { id: "minecraft:looting", name: "Looting" },
  { id: "minecraft:sweeping_edge", name: "Sweeping Edge" },
  { id: "minecraft:efficiency", name: "Efficiency" },
  { id: "minecraft:silk_touch", name: "Silk Touch" },
  { id: "minecraft:unbreaking", name: "Unbreaking" },
  { id: "minecraft:fortune", name: "Fortune" },
  { id: "minecraft:power", name: "Power" },
  { id: "minecraft:punch", name: "Punch" },
  { id: "minecraft:flame", name: "Flame" },
  { id: "minecraft:infinity", name: "Infinity" },
  { id: "minecraft:mending", name: "Mending" },
  { id: "minecraft:protection", name: "Protection" },
  { id: "minecraft:fire_protection", name: "Fire Protection" },
  { id: "minecraft:feather_falling", name: "Feather Falling" },
  { id: "minecraft:blast_protection", name: "Blast Protection" },
  { id: "minecraft:projectile_protection", name: "Proj Protection" },
  { id: "minecraft:respiration", name: "Respiration" },
  { id: "minecraft:aqua_affinity", name: "Aqua Affinity" },
  { id: "minecraft:thorns", name: "Thorns" },
  { id: "minecraft:depth_strider", name: "Depth Strider" },
  { id: "minecraft:frost_walker", name: "Frost Walker" },
  { id: "minecraft:soul_speed", name: "Soul Speed" },
  { id: "minecraft:swift_sneak", name: "Swift Sneak" },
  { id: "minecraft:density", name: "Density (Mace)" },
  { id: "minecraft:breach", name: "Breach (Mace)" },
  { id: "minecraft:wind_burst", name: "Wind Burst (Mace)" },
  { id: "minecraft:multishot", name: "Multishot" },
  { id: "minecraft:quick_charge", name: "Quick Charge" },
  { id: "minecraft:piercing", name: "Piercing" },
  { id: "minecraft:loyalty", name: "Loyalty" },
  { id: "minecraft:impaling", name: "Impaling" },
  { id: "minecraft:riptide", name: "Riptide" },
  { id: "minecraft:channeling", name: "Channeling" },
];
